CREATE TABLE public.users (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(25) NOT NULL,
  password varchar(100) NOT NULL,
  enabled  boolean NOT NULL,
  authority varchar(50) NOT NULL,
  PRIMARY KEY (username)
) ;

INSERT INTO public.users (username, password, enabled, authority)
VALUES
	('admin', '{noop}Fafwt34q7j', true, 'ADMIN');
